### PR TITLE
fix(libre-sys): upgrade bindgen to 0.72 for Rust 2024 edition compati…

### LINKED ISSUE #2: libre-sys fails to compile on Rust 2024 edition due to bindgen-generated unsafe code
Summary
libre-sys fails to compile with Rust 1.85+ (edition 2024) because the bindgen-generated bitfield code uses unsafe operations inside unsafe fn bodies without explicit unsafe {} blocks. The Rust 2024 edition enforces unsafe_op_in_unsafe_fn by default, and the workspace [lints.rust] warnings = "deny" turns this into a hard error.

Steps to Reproduce
cargo run --release -p cdma-voice-gw -- --config config/voice-gw.json

Error Output
```
error[E0133]: dereference of raw pointer is unsafe and requires unsafe block
  --> .../out/bindgen.rs:39:20
   |
39 |         let byte = *(core::ptr::addr_of!((*this).storage) as *const u8).offset(byte_index as isize);
   |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: `-D unsafe-op-in-unsafe-fn` implied by `-D warnings`

error: unnecessary transmute
   --> .../out/bindgen.rs:254:18
    |
254 |         unsafe { ::std::mem::transmute(self._bitfield_1.get(0usize, 24u8) as u32) }
    = note: `-D unnecessary-transmutes` implied by `-D warnings`

error: could not compile `libre-sys` (lib) due to 14 previous errors
```

Two categories of errors in the generated bindgen.rs:

unsafe_op_in_unsafe_fn (9 errors) — raw pointer dereferences and unsafe function calls inside unsafe fn without explicit unsafe {} blocks.
unnecessary_transmutes (5 errors) — std::mem::transmute on same-size integer casts that Rust 1.84+ flags as unnecessary.

Environment
rustc: 1.95.0 (2024 edition)
bindgen: 0.71
libre-sys edition: 2024
OS: Linux

Root Cause
bindgen 0.71 generates bitfield accessor code that predates the Rust 2024 edition's requirement for explicit unsafe {} blocks inside unsafe fn. The workspace lint warnings = "deny" promotes these to hard errors.

### PR DESCRIPTION
**Pull request by VasylSamoilov**
…bility

Bindgen 0.71 generated code that violated unsafe_op_in_unsafe_fn (required by edition 2024). Upgrading to 0.72 fixes that. Remaining cosmetic lints (unnecessary_transmutes, ptr_offset_with_cast, missing_safety_doc) are suppressed per standard practice for machine-generated FFI bindings.

Fixes #2

### CODE REVIEW

**Comment by VasylSamoilov** [comment]
CI failure has nothing to do with my change, curl failed to fetch capture.

**Comment by chrismoos** [comment]
> CI failure has nothing to do with my change, curl failed to fetch capture.

Should be fixed now, can you update this branch to latest `main`?

**Comment by VasylSamoilov** [comment]
> > CI failure has nothing to do with my change, curl failed to fetch capture.
> 
> Should be fixed now, can you update this branch to latest `main`?

Updated

**Review by chrismoos — APPROVED** [review]
